### ISSUE TITLE
Reset all containers

### ISSUE THREAD

**Issue by ChilicookieZ** [cafestifflered/ContainerFaker#15]
When replacing an item with a new version (different stats for example) would it be possible to reset all containers as we’re realising the old versions remain in containers and could be there for weeks until a player actually clicks it to reset the timer.

**Comment by cafestifflered** [comment]
```/containerfaker clearcache```

**Comment by cafestifflered** [comment]
Make sure this doesn't reset any individual or region container category overrides

**Comment by Owen1212055** [comment]
Cache is now cleared when pool is updated/on command.
