### ISSUE TITLE
Check the type of container to see if it's following the override

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ContainerFaker#7]
There may be an issue with some containers not properly following the override. Some containers are set to be food, but the client used /containeroverride to change them to junk. When using that command, the container turns green for a moment to show it was successful.

However, after some time they went back and found that the containers were still giving food instead of junk. Two requests:

- ~~Add a command `/containeroverride check` and permission to see what the loot pool is for a specific container~~ [Resolved](https://github.com/cafestifflered/ContainerFaker/commit/e54221d6ce55e56bd5ce33565232784edad034ea)
- Double check that the logic for saving the override types is working

**Comment by Owen1212055** [comment]
I wasn't able to reproduce any sort of weird override saving issues, and it doesn't make sense why something like that could happen.

Please let me know if anything pops up, but make sure that the client is properly saving their world.
